### ISSUE TITLE
봉사활동 목록 관심사 분류 로직 구현

### ISSUE THREAD

**Issue by Jun-Young-Seo** [Jun-Young-Seo/HSP#5]
# 봉사활동 목록 관심사 분류 로직 구현 이슈

크롤링 스크립트가 실행될 때 마다 약 7000개의 봉사활동을 매일 분류해야합니다.

기획팀에서 설정한 봉사활동 관심사는

**'교육' '상담' '환경' '활동보조' '활동참여' '캠페인'** 입니다.

### 1. NLP 기법 활용

- 구현 난이도 어려움
-  시스템 크기가 너무 클지도

### 2. 머신 러닝 활용

- 마찬가지로 구현 난이도 어려움(어차피 NLP를 해야 처리 러닝 데이터 처리로 활용 가능)
- BERT 모델 등 여러가지 시도를 해봤지만, 라벨링 데이터가 있는 것도 아니고, 라벨링 할 인력도 없음.

### 3. 1365 데이터 중 키워드로 분류하는 방식

- 제목에 '환경', '환경미화' 등의 키워드가 포함되어 있으면 '환경' 관심사로 분류하는 방식.
- 구현이 매우 간단합니다.
- 하지만, 키워드에 포함되지 못하는 봉사활동이 생길 가능성이 높습니다.

### 4. 수동

- 7000개를 다하는거는 무리고, 키워드에서 분류되지 못한 봉사활동에 대해서만 진행.
- 누가? 어떻게? 그것도 매일매일?

### 5. 1365에서 분류해둔 시스템을 추가 활용

- 봉사활동이 업로드되는 방식은 확인할 수 없지만, 아마 업로드하는 사람이 미리 정해서 업로드 하는 것 같습니다. 봉사활동 제목을 직접 클릭해 세부 페이지로 이동하면 봉사활동의 분류를 확인할 수 있습니다.
- 현재 크롤링 로직이 bs4로 구현되어 있어, 직접 URL에 들어가 분류를 확인해오는 방식은 시간 소모가 상당합니다. 현재도 매일 약 700페이지의 크롤링이 자동으로 진행되는데, 한 페이지에 10개의 봉사활동 목록이 있으니 매일 7000개의 페이지로 직접 이동해 크롤링합니다.
- GET 방식(URL 쿼리로 봉사활동 업로드)으로 봉사활동 세부 페이지가 업로드되는건 맞지만, 모집 기간이 지난 페이지(신청 불가)와 모집이 진행 중인 페이지의 URL 쿼리 규칙을 찾아낼 수 없었습니다.
- 현재 700페이지 크롤링에 걸리는 시간 (Network delay 포함) 약 30분
- 7000페이지로 변경하면 => 시간 소모가 너무 큽니다. 그 시간 동안 웹앱서버를 멈춰둘 수도 없습니다.

**Comment by DongHyun0521** [comment]
3번 방식이 그나마 실현 가능성이 높아 보입니다. 대신 저희가 몇몇 봉사활동 페이지들을 들어가서 내용을 읽어보며 키워드를 좀 많이 여러개 지정해 놓으면 그나마 미분류되는 봉사활동이 적어지지 않을까요?

**Comment by Jun-Young-Seo** [comment]
def classify_keyword(keyword, keyword_detail):
    # 키워드 매핑
    keyword_mapping = {
        '교육': ['교육', '강의', '교사', '학습', '멘토링'],
        '상담': ['상담', '코칭', '멘토링'],
        '환경': ['환경', '청소', '정화', '미화', '환경보호'],
        '활동보조': ['보조', '도움', '지원', '생활편의지원'],
        '활동참여': ['참여', '봉사', '활동', '행사보조'],
        '캠페인': ['캠페인', '홍보', '프로모션']
    }

    # 모든 키워드 매핑에 대해 검색
    for category, terms in keyword_mapping.items():
        if keyword in terms or keyword_detail in terms:
            return category

    return '기타'

이 코드와 크롤링 로직을 수정해 문제 해결했습니다.
1365 사이트에서 제공하는 대분류 > 소분류 둘 다 크롤링하고, 둘 중 하나라도 키워드에 매핑되면 분류하는 방식입니다.
'기타'에 분류되는 경우는 없거나 극히 작음을 확인했습니다. 키워드 매핑 사전에 추가해 더 줄일 수 있습니다.


해결로 이슈 닫습니다.

**Comment by Jun-Young-Seo** [comment]
해결로 이슈 닫습니다.
